management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh,health
#spring:
#    datasource:
#        url: jdbc:mysql://localhost:3306/feature_flags_configuration
#        username: root
#        password: root
#        driverClassName: com.mysql.cj.jdbc.Driver
#    liquibase:
#        change-log: classpath:db/changelog/db.changelog-master.xml